apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-front
  namespace: default
  labels:
    app: lb-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lb-front
  template:
    metadata:
      labels:
        app: lb-front
    spec:
      containers:
      - name: front
        image: meanfront
        imagePullPolicy: Never  # or IfNotPresent
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "8000"
        - name: API_IP
          value: "${MASTER_IP}"
        - name: API_PORT
          value: "30000"
        - name: DEV_PORT
          value: "10010"
---


apiVersion: v1
kind: Service
metadata:
  name: "lb-front"
  annotations:
    # Create endpoints also if the related pod isn't ready
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 4200
    nodePort: 30005
    targetPort: 4200
  selector:
    app: lb-front
