apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbfront
  namespace: default
  labels:
    app: lbfront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lbfront
  template:
    metadata:
      labels:
        app: lbfront
    spec:
      containers:
      - name: front
        image: meanfront
        imagePullPolicy: Never  # or IfNotPresent
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: API_IP
          value: "172.18.0.2"
        - name: API_PORT
          value: "30000"
        - name: DEV_PORT
          value: "10010"
        command: ["/bin/sh"]
        args: ["sed -i "s/myiphere:myporthere/$API_IP:$API_PORT/g" src/environments/environment.ts","sed -i "s/myiphere:myporthere/$API_IP:$API_PORT/g" src/environments/environment.prod.ts","npm start"]
---


apiVersion: v1
kind: Service
metadata:
  name: "lbfront"
  annotations:
    # Create endpoints also if the related pod isn't ready
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 4200
    nodePort: 30005
    targetPort: 4200
  selector:
    app: lbfront
